/* eslint-disable */
// @ts-nocheck
// @generated by scripts/sync-forks.mjs. Do not edit.
//
// Compiled StyleX from @astryxdesign/lab 0.6.2-canary.c9fb1ad, reused by the
// Tour fork so it renders with upstream's own class names
// (src/forks/compiled.ts). Copyright (c) Meta Platforms, Inc. and
// affiliates; MIT, see NOTICE.

// dist/Tour/TourStep.js
export const styles = {
  footer: {
    kGNEyG: "x6s0dn4",
    kjj79g: "x1qughib",
    $$css: true,
  },
  calloutGapBelow: {
    keoZOQ: "xtbrsbv",
    $$css: true,
  },
  calloutGapAbove: {
    k1K539: "x1p37lm5",
    $$css: true,
  },
  calloutGapStart: {
    k71WvV: "x1pezmd8",
    $$css: true,
  },
  calloutGapEnd: {
    keTefX: "x1cmpsy9",
    $$css: true,
  },
};
