/* eslint-disable */
// @ts-nocheck
// @generated by scripts/sync-forks.mjs. Do not edit.
//
// Compiled StyleX from @astryxdesign/core 0.6.5, reused by the
// ComplexSelector fork so it renders with upstream's own class names
// (src/forks/compiled.ts). Copyright (c) Meta Platforms, Inc. and
// affiliates; MIT, see NOTICE.

// dist/ComplexSelector/ComplexSelector.js
export const styles = {
  triggerContainer: {
    kVAEAm: "x1n2onr6",
    k1xSpc: "x78zum5",
    kGNEyG: "x6s0dn4",
    kjj79g: "x1qughib",
    kOIVth: "x1txdalj",
    kzqmXN: "xh8yej3",
    k8WAf4: "xce4md1",
    kg3NbH: "xrrkdod",
    kMv6JI: "x9ynric",
    kGuDYH: "xcr08ib x1w61h2b",
    kLWn49: "x1kq96og",
    kMwMTN: "x1tgivj0",
    kkrTdU: "x1ypdohk x16khyan",
    $$css: true,
  },
  trigger: {
    k1xSpc: "x78zum5",
    kGNEyG: "x6s0dn4",
    kjj79g: "x1qughib",
    kOIVth: "x1txdalj",
    kzQI83: "x1iyjqo2",
    kmuXW: "xs83m0k",
    kCS8Yb: "x1r8uery",
    k7Eaqz: "xeuugli",
    kmVPX3: "x1717udv",
    kogj98: "x1ghz6dp",
    kMzoRj: "xc342km",
    ksu8eU: "xng3xce",
    kWkggS: "xjbqb8w",
    kMv6JI: "xjb2p0i",
    kGuDYH: "x1qlqyl8",
    kLWn49: "x15bjb6t",
    kMwMTN: "x1heor9g",
    kkrTdU: "x1ypdohk x16khyan",
    kI3sdo: "x1a2a7pz",
    kaIpWk: "xh6dtrn",
    $$css: true,
  },
  triggerText: {
    kzQI83: "x1iyjqo2",
    k7Eaqz: "xeuugli",
    kVQacm: "xb3r6kr",
    kg5iWk: "xlyipyv",
    khDVqt: "xuxw1ft",
    k9WMMc: "x1yc453h",
    $$css: true,
  },
  placeholder: {
    kMwMTN: "xv1l7n4",
    $$css: true,
  },
  triggerGhost: {
    kzqmXN: "x14atkfc",
    kMzoRj: "xc342km",
    kWkggS: "xjbqb8w",
    kGVxlE: "x1gnnqk1 x1s17dad x15ysqaf",
    k63SB2: "x1e4wzip",
    k1ekBW: "xrafxwg",
    k3aq6I: "x3oybdh xk4oym4",
    $$css: true,
  },
  triggerGhostDisabled: {
    kKwaWg: "x18o3ruo",
    k3aq6I: "x1c071of x1pdlv7q",
    $$css: true,
  },
  triggerIcon: {
    kmuXW: "x2lah0s",
    $$css: true,
  },
  triggerIconRotation: {
    k1ekBW: "x11xpdln",
    kIyJzY: "xuedmi6",
    kAMwcw: "xlr8y92",
    k3nNDw: "x1g0ag68",
    $$css: true,
  },
  triggerIconOpen: {
    k3aq6I: "x19jd1h0",
    $$css: true,
  },
  popover: {
    k7Eaqz: "xrzjruh",
    $$css: true,
  },
  content: {
    kB7OPa: "x9f619",
    kskxy: "xpnbb6b",
    kVQacm: "xysyzu8",
    kmVPX3: "x1b2ylru",
    $$css: true,
  },
  sm: {
    kZKoxP: "x6k0iem",
    $$css: true,
  },
  md: {
    kZKoxP: "x1ueg155",
    $$css: true,
  },
  lg: {
    kZKoxP: "xssyfek",
    $$css: true,
  },
  disabled: {
    kkrTdU: "xt0e3qv",
    $$css: true,
  },
};

// dist/utils/interactionOverlay.stylex.js
export const interactionOverlayStyles = {
  backgroundColor: {
    kWkggS: "xjbqb8w x1anq1lc xoevpu5 xprvw0a",
    $$css: true,
  },
  backgroundImage: {
    kKwaWg: "x7uyq82 xmvprkv xetgvay",
    $$css: true,
  },
  backgroundImageOnNeutral: {
    kKwaWg: "x14bno8m xzmimnh x1otsd3y xo3fi6e",
    $$css: true,
  },
  pressedBackgroundColor: {
    kWkggS: "x1anq1lc",
    $$css: true,
  },
};
