/**
 * Export-surface generator.
 *
 * ui-common mirrors Astryx 1:1. Every subpath in the `exports` map of
 * `@astryxdesign/core` becomes the same subpath here, `@astryxdesign/lab`
 * becomes `lab`, and `@astryxdesign/theme-neutral` becomes `theme/neutral`.
 * Nothing is curated by hand. The only way to hide a subpath is an entry in
 * `exports.exclude.json`.
 *
 * Outputs, all committed:
 *
 * - `src/astryx/**`: one re-export file per mirrored subpath. A JS subpath is
 *   `export * from "<astryx specifier>"`. A CSS subpath is one `@import`.
 * - `src/index.ts`: the root barrel. Explicit named re-exports of core's root
 *   (minus the names of excluded subpaths), plus the ui-common customs listed
 *   in `exports.customs.json`.
 * - `package.json#exports`.
 *
 * `src/exports.test.ts` runs `generate()` in memory and byte-compares the
 * result with the committed files, so the build goes red on every Astryx
 * bump until this script is re-run and the diff is reviewed.
 *
 * Usage: `pnpm run gen:exports`
 */
import { readFile, readdir, rm, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import * as prettier from "prettier";
import ts from "typescript";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Where the mirrored re-export files live, relative to the repository. */
export const MIRROR_DIR = "src/astryx";

const GENERATED_HEADER = "@generated by scripts/gen-exports.mjs. Do not edit.";

/** Astryx packages mirrored, and the ui-common subpath each one lands under. */
export const MIRRORED_PACKAGES = [
  { name: "@astryxdesign/core", prefix: "" },
  { name: "@astryxdesign/lab", prefix: "lab" },
  { name: "@astryxdesign/theme-neutral", prefix: "theme/neutral" },
];

/**
 * ui-common's own subpaths. Everything else in the exports map is mirrored.
 * Adding one here is a decision about the public surface, so it is code, not
 * data.
 */
export const OWN_EXPORTS = {
  ".": { types: "./dist/index.d.ts", import: "./dist/index.js" },
  "./components/*": {
    types: "./dist/components/*/index.d.ts",
    import: "./dist/components/*/index.js",
  },
  "./theme/lablup": {
    types: "./dist/theme/lablup/index.d.ts",
    import: "./dist/theme/lablup/index.js",
  },
  "./theme/lablup/built": {
    types: "./dist/theme/lablup/built/lablup.d.ts",
    import: "./dist/theme/lablup/built/lablup.js",
  },
  "./theme/lablup/theme.css": "./dist/theme/lablup/built/theme.css",
  "./ui-common.css": "./dist/ui-common.css",
  "./legacy-tokens.css": "./dist/legacy-tokens.css",
  "./styles/base.css": "./dist/styles/base.css",
  "./styles/themes/*.css": "./dist/styles/themes/*.css",
};

/** The locale catalogs are JSON, so they are merged at build time instead. */
const LOCALES_PATTERN = "./locales/*.json";

/**
 * The installed package's directory. Read through node_modules rather than
 * `require.resolve`, because Astryx does not export `./package.json`.
 */
function packageDir(name) {
  const dir = join(root, "node_modules", name);
  if (!existsSync(join(dir, "package.json"))) {
    throw new Error(`${name} is not installed. Run pnpm install first.`);
  }
  return dir;
}

async function readJson(path) {
  return JSON.parse(await readFile(path, "utf8"));
}

function posix(path) {
  return path.split(sep).join("/");
}

/** `{ name, replacedBy, reason }[]` from exports.exclude.json, validated. */
async function readExclusions() {
  const list = await readJson(join(root, "exports.exclude.json"));
  if (!Array.isArray(list)) throw new Error("exports.exclude.json must be an array");
  for (const entry of list) {
    if (typeof entry?.name !== "string" || typeof entry?.reason !== "string") {
      throw new Error(
        `exports.exclude.json: every entry needs "name" and "reason": ${JSON.stringify(entry)}`,
      );
    }
    if (!("replacedBy" in entry)) {
      throw new Error(
        `exports.exclude.json: "${entry.name}" needs "replacedBy" (use null when nothing replaces it)`,
      );
    }
  }
  return list;
}

/** `{ name, source, subpath?, legacy? }[]` from exports.customs.json, validated. */
async function readCustoms() {
  const list = await readJson(join(root, "exports.customs.json"));
  if (!Array.isArray(list)) throw new Error("exports.customs.json must be an array");
  for (const entry of list) {
    if (typeof entry?.name !== "string" || typeof entry?.source !== "string") {
      throw new Error(
        `exports.customs.json: every entry needs "name" and "source": ${JSON.stringify(entry)}`,
      );
    }
    if (!existsSync(join(root, "src", entry.source))) {
      throw new Error(
        `exports.customs.json: "${entry.name}" source src/${entry.source} does not exist`,
      );
    }
  }
  return list;
}

/**
 * Every mirrored subpath: which Astryx specifier it re-exports, and whether it
 * is a script module or a stylesheet.
 */
async function collectMirroredSubpaths() {
  const subpaths = [];
  for (const { name, prefix } of MIRRORED_PACKAGES) {
    const dir = packageDir(name);
    const pkg = await readJson(join(dir, "package.json"));
    for (const [key, value] of Object.entries(pkg.exports ?? {})) {
      if (key === "./package.json") continue;
      const rest = key === "." ? "" : key.slice(2);
      const subpath = [prefix, rest].filter(Boolean).join("/");
      const specifier = rest === "" ? name : `${name}/${rest}`;
      const target =
        typeof value === "string" ? value : (value.default ?? value.import);
      subpaths.push({
        package: name,
        packageDir: dir,
        key,
        subpath,
        specifier,
        types: typeof value === "string" ? undefined : value.types,
        target,
        // Core's own root is not a mirror file: it is the root barrel,
        // written out name by name below.
        kind:
          subpath === ""
            ? "root"
            : key.includes("*")
              ? "pattern"
              : key.endsWith(".css")
                ? "css"
                : /\.m?js$/.test(key)
                  ? "data"
                  : "js",
      });
    }
  }
  return subpaths;
}

/**
 * Names a module exports, split into runtime values and type-only names.
 * Read through the TypeScript checker so `export type { X }` is recognised
 * even when `X` also names a value somewhere down the re-export chain.
 */
function moduleExports(checker, sourceFile) {
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
  if (!moduleSymbol) return { values: [], types: [] };
  const values = [];
  const types = [];
  for (const symbol of checker.getExportsOfModule(moduleSymbol)) {
    const name = symbol.getName();
    if (name === "default") continue;
    if (isTypeOnly(checker, symbol)) {
      types.push(name);
      continue;
    }
    const target =
      symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
    if (target.flags & ts.SymbolFlags.Value) values.push(name);
    else types.push(name);
  }
  return { values: values.sort(), types: types.sort() };
}

function hasDefaultExport(checker, sourceFile) {
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
  if (!moduleSymbol) return false;
  return checker
    .getExportsOfModule(moduleSymbol)
    .some((s) => s.getName() === "default");
}

function isTypeOnly(checker, symbol) {
  const seen = new Set();
  let current = symbol;
  while (current && current.flags & ts.SymbolFlags.Alias && !seen.has(current)) {
    seen.add(current);
    for (const declaration of current.declarations ?? []) {
      if (ts.isExportSpecifier(declaration) || ts.isImportSpecifier(declaration)) {
        if (declaration.isTypeOnly || declaration.parent.parent.isTypeOnly) return true;
      }
      if (ts.isImportClause(declaration) && declaration.isTypeOnly) return true;
      if (ts.isNamespaceExport(declaration) && declaration.parent.isTypeOnly)
        return true;
    }
    current = checker.getImmediateAliasedSymbol(current);
  }
  return false;
}

function createProgram(files) {
  return ts.createProgram(files, {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    jsx: ts.JsxEmit.ReactJSX,
    allowJs: false,
    skipLibCheck: true,
    noEmit: true,
    types: [],
  });
}

function jsFile(subpath) {
  return `${MIRROR_DIR}/${subpath}.ts`;
}

function cssFile(subpath) {
  return `${MIRROR_DIR}/${subpath}`;
}

/** Relative import specifier from src/index.ts to a custom's source file. */
function customSpecifier(source) {
  const withoutExt = source.replace(/\.tsx?$/, "").replace(/\/index$/, "");
  return `./${withoutExt}`;
}

/** A list as ` * `-prefixed comment lines of at most 80 columns. */
function wrapComment(names) {
  const lines = [];
  let line = "";
  for (const [i, name] of names.entries()) {
    const word = `${name}${i === names.length - 1 ? "." : ","}`;
    if (line && ` * ${line} ${word}`.length > 80) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines.map((l) => ` * ${l}\n`).join("");
}

function exportList(keyword, names, from) {
  if (names.length === 0) return "";
  return `${keyword} {\n${names.map((n) => `  ${n},`).join("\n")}\n} from "${from}";\n`;
}

async function format(content, filepath) {
  const config = (await prettier.resolveConfig(join(root, filepath))) ?? {};
  return prettier.format(content, { ...config, filepath: join(root, filepath) });
}

/**
 * Compute every output in memory. Returns
 * `{ files: Map<repoRelativePath, content>, exports, report }`.
 */
export async function generate() {
  const exclusions = await readExclusions();
  const customs = await readCustoms();
  const excludedNames = new Set(exclusions.map((e) => e.name));
  const all = await collectMirroredSubpaths();

  const known = new Set(all.map((s) => s.subpath));
  for (const name of excludedNames) {
    if (!known.has(name)) {
      throw new Error(
        `exports.exclude.json names "${name}", which no mirrored package exports any more. ` +
          `Remove the entry.`,
      );
    }
  }

  const mirrored = all.filter((s) => !excludedNames.has(s.subpath));
  const excluded = all.filter((s) => excludedNames.has(s.subpath));

  for (const s of mirrored) {
    if (s.kind === "data") {
      throw new Error(
        `${s.package} exports "${s.key}", a data module ui-common does not know how to mirror. ` +
          `Mirror it deliberately or add it to exports.exclude.json.`,
      );
    }
    if (
      s.kind === "pattern" &&
      !(s.package === "@astryxdesign/core" && s.key === LOCALES_PATTERN)
    ) {
      throw new Error(
        `${s.package} exports the pattern "${s.key}", which the generator does not handle.`,
      );
    }
  }

  // Type information: every mirrored JS module (to find default exports),
  // core's root, the excluded modules (their names leave the root barrel),
  // lab's root (for the name rule), and each custom's source.
  const coreDir = packageDir("@astryxdesign/core");
  const labDir = packageDir("@astryxdesign/lab");
  const typesPath = (s) => (s.types ? join(s.packageDir, s.types) : undefined);
  const coreRootTypes = join(coreDir, "dist/index.d.ts");
  const labRootTypes = join(labDir, "dist/index.d.ts");
  const customPaths = customs.map((c) => join(root, "src", c.source));
  const jsSubpaths = all.filter((s) => s.kind === "js");
  const program = createProgram([
    coreRootTypes,
    labRootTypes,
    ...jsSubpaths.map(typesPath).filter(Boolean),
    ...customPaths,
  ]);
  const checker = program.getTypeChecker();
  const sourceOf = (path) => {
    const file = program.getSourceFile(path);
    if (!file) throw new Error(`TypeScript could not load ${relative(root, path)}`);
    return file;
  };

  const files = new Map();

  // 1. Mirrored re-export files.
  for (const s of mirrored) {
    if (s.kind === "js") {
      const path = jsFile(s.subpath);
      const types = typesPath(s);
      const hasDefault = types ? hasDefaultExport(checker, sourceOf(types)) : false;
      let body = `// ${GENERATED_HEADER}\nexport * from "${s.specifier}";\n`;
      if (hasDefault) body += `export { default } from "${s.specifier}";\n`;
      files.set(path, await format(body, path));
    } else if (s.kind === "css") {
      const path = cssFile(s.subpath);
      files.set(
        path,
        await format(`/* ${GENERATED_HEADER} */\n@import "${s.specifier}";\n`, path),
      );
    }
  }

  // 2. Root barrel.
  const coreRoot = moduleExports(checker, sourceOf(coreRootTypes));
  const labRoot = moduleExports(checker, sourceOf(labRootTypes));

  // Cross-check the classification against what core actually exports at
  // runtime. A mismatch means a type-only name would be emitted as a value
  // (a runtime SyntaxError for consumers) or the reverse.
  const runtime = Object.keys(
    await import(pathToFileURL(join(coreDir, "dist/index.js")).href),
  )
    .filter((n) => n !== "default")
    .sort();
  if (JSON.stringify(runtime) !== JSON.stringify(coreRoot.values)) {
    const onlyRuntime = runtime.filter((n) => !coreRoot.values.includes(n));
    const onlyTypes = coreRoot.values.filter((n) => !runtime.includes(n));
    throw new Error(
      `Value/type classification of @astryxdesign/core disagrees with its runtime exports. ` +
        `Runtime only: ${onlyRuntime.join(", ") || "-"}. Declared only: ${onlyTypes.join(", ") || "-"}.`,
    );
  }

  const droppedFromRoot = new Set();
  for (const s of excluded.filter(
    (e) => e.kind === "js" && e.package === "@astryxdesign/core",
  )) {
    const types = typesPath(s);
    if (!types) continue;
    const names = moduleExports(checker, sourceOf(types));
    for (const n of [...names.values, ...names.types]) droppedFromRoot.add(n);
  }

  const coreValues = coreRoot.values.filter((n) => !droppedFromRoot.has(n));
  const coreTypes = coreRoot.types.filter((n) => !droppedFromRoot.has(n));
  const coreNames = new Set([...coreRoot.values, ...coreRoot.types]);
  const labNames = new Set([...labRoot.values, ...labRoot.types]);

  const report = { droppedFromRoot: [...droppedFromRoot].sort(), legacyCollisions: [] };
  const customBlocks = [];
  const rootNames = new Set([...coreValues, ...coreTypes]);

  for (const custom of customs) {
    const names = moduleExports(checker, sourceOf(join(root, "src", custom.source)));
    // A legacy entry deprecates the names it lists, or its whole module when
    // it lists none. Only a deprecated name may collide with Astryx.
    const deprecated = (n) =>
      custom.legacy !== undefined &&
      (custom.legacy.names === undefined || custom.legacy.names.includes(n));
    const keep = { values: [], types: [] };
    for (const [bucket, list] of [
      ["values", names.values],
      ["types", names.types],
    ]) {
      for (const n of list) {
        const clashCore = coreNames.has(n);
        const clashLab = labNames.has(n);
        if ((clashCore || clashLab) && !deprecated(n)) {
          throw new Error(
            `exports.customs.json: "${custom.name}" exports "${n}", which ${
              clashCore ? "@astryxdesign/core" : "@astryxdesign/lab"
            } also exports. ui-common customs never share a name with Astryx.`,
          );
        }
        if (clashCore) {
          report.legacyCollisions.push(n);
          continue;
        }
        if (rootNames.has(n)) {
          throw new Error(
            `exports.customs.json: "${n}" is exported twice from the root barrel.`,
          );
        }
        rootNames.add(n);
        keep[bucket].push(n);
      }
    }
    if (keep.values.length + keep.types.length === 0) continue;
    const from = customSpecifier(custom.source);
    let comment = `// ${custom.name}\n`;
    if (custom.legacy) {
      const what = custom.legacy.names ? custom.legacy.names.join(", ") : "this module";
      comment += `// Deprecated, removed in 0.3: ${what}. Replaced by ${custom.legacy.replacedBy}.\n`;
    }
    customBlocks.push(
      comment +
        exportList("export", keep.values, from) +
        exportList("export type", keep.types, from),
    );
  }

  const barrel =
    `/**\n * ${GENERATED_HEADER}\n *\n` +
    ` * The root barrel: Astryx core's root exports, minus the names of the\n` +
    ` * subpaths in exports.exclude.json, then the ui-common customs listed in\n` +
    ` * exports.customs.json. Edit those files and run \`pnpm run gen:exports\`.\n` +
    (report.droppedFromRoot.length > 0
      ? ` *\n * Left out because their subpath is excluded:\n${wrapComment(report.droppedFromRoot)}`
      : "") +
    (report.legacyCollisions.length > 0
      ? ` *\n * Deprecated customs whose names Astryx owns. The Astryx export wins\n` +
        ` * here; the custom stays at @lablup/ui-common/components/<Name> until 0.3:\n` +
        wrapComment(report.legacyCollisions)
      : "") +
    ` */\n\n` +
    exportList("export", coreValues, "@astryxdesign/core") +
    exportList("export type", coreTypes, "@astryxdesign/core") +
    `\n` +
    customBlocks.join("\n");
  files.set("src/index.ts", await format(barrel, "src/index.ts"));

  // 3. The exports map.
  const exportsMap = { ...OWN_EXPORTS };
  for (const s of mirrored) {
    if (s.kind === "js") {
      exportsMap[`./${s.subpath}`] = {
        types: `./dist/astryx/${s.subpath}.d.ts`,
        import: `./dist/astryx/${s.subpath}.js`,
      };
    } else if (s.kind === "css") {
      exportsMap[`./${s.subpath}`] = `./dist/astryx/${s.subpath}`;
    } else if (s.kind === "pattern") {
      exportsMap[LOCALES_PATTERN] = "./dist/locales/*.json";
    }
  }
  for (const custom of customs) {
    if (!custom.subpath) continue;
    const key = `./${custom.subpath}`;
    if (key in exportsMap) {
      throw new Error(
        `exports.customs.json: subpath "${custom.subpath}" is already taken.`,
      );
    }
    if (known.has(custom.subpath)) {
      throw new Error(
        `exports.customs.json: subpath "${custom.subpath}" is an Astryx subpath (even if excluded).`,
      );
    }
    const base = custom.source.replace(/\.tsx?$/, "");
    exportsMap[key] = { types: `./dist/${base}.d.ts`, import: `./dist/${base}.js` };
  }
  exportsMap["./package.json"] = "./package.json";

  return { files, exports: exportsMap, report };
}

/** Every file currently under the mirror directory, repository-relative. */
export async function listMirrorFiles() {
  const out = [];
  async function walk(dir) {
    if (!existsSync(dir)) return;
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) await walk(path);
      else out.push(posix(relative(root, path)));
    }
  }
  await walk(join(root, MIRROR_DIR));
  return out.sort();
}

async function main() {
  const { files, exports: exportsMap, report } = await generate();

  for (const stale of await listMirrorFiles()) {
    if (!files.has(stale)) await rm(join(root, stale));
  }
  for (const [path, content] of files) {
    await mkdir(dirname(join(root, path)), { recursive: true });
    await writeFile(join(root, path), content);
  }

  const pkgPath = join(root, "package.json");
  const pkg = await readJson(pkgPath);
  pkg.exports = exportsMap;
  await writeFile(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

  console.log(
    `Wrote ${files.size} file(s) and ${Object.keys(exportsMap).length} export path(s).`,
  );
  if (report.droppedFromRoot.length > 0) {
    console.log(`Excluded from the root barrel: ${report.droppedFromRoot.join(", ")}`);
  }
  if (report.legacyCollisions.length > 0) {
    console.log(
      `Deprecated custom names Astryx owns: ${report.legacyCollisions.join("; ")}`,
    );
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
