/**
 * Upkeep for the Astryx forks under src/forks/ (CONTRIBUTING, "Forks of
 * Astryx components").
 *
 * `src/forks/provenance.json` records, for each fork, the Astryx package and
 * version it was taken from, a SHA-256 of every upstream file it copies or
 * compiles from, and which compiled StyleX constants it reuses. From that:
 *
 * - `<fork>.styles.ts` is generated: the named constants, copied verbatim from
 *   the pinned package's compiled `dist/` file. The fork renders with
 *   upstream's own atomic class names, so it needs no StyleX compile step and
 *   no CSS of its own (src/forks/compiled.ts).
 * - `src/forks/forks.test.ts` fails when the installed Astryx differs from the
 *   recorded version or any recorded file changed, and when a styles file is
 *   stale. An Astryx bump therefore stops CI until someone re-syncs the fork
 *   with upstream (or deletes it, once upstream carries the fix).
 *
 * Usage:
 *   node scripts/sync-forks.mjs           rewrite the styles files
 *   node scripts/sync-forks.mjs --accept  also record the installed versions
 *                                         and hashes, after re-syncing by hand
 */
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import * as prettier from "prettier";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export const PROVENANCE = "src/forks/provenance.json";

const GENERATED_HEADER = "@generated by scripts/sync-forks.mjs. Do not edit.";

/** @returns {Record<string, {package: string, version: string, upstream: string, files: Record<string,string>, styles?: {file: string, from: Array<{file: string, consts: string[]}>}}>} */
export function readProvenance() {
  return JSON.parse(readFileSync(join(root, PROVENANCE), "utf8"));
}

export function packageDir(name) {
  const dir = join(root, "node_modules", name);
  if (!existsSync(join(dir, "package.json"))) {
    throw new Error(`${name} is not installed. Run pnpm install first.`);
  }
  return dir;
}

export function installedVersion(name) {
  return JSON.parse(readFileSync(join(packageDir(name), "package.json"), "utf8"))
    .version;
}

export function sha256(path) {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

/**
 * The source text of the top-level `const <name> = …;` (or `export const`) in
 * a compiled Astryx module: from `const` to the `;` that closes it at depth 0.
 * Strings and comments are skipped so a brace inside a class list or a
 * comment never miscounts.
 */
export function extractConst(source, name) {
  const match = new RegExp(`^(?:export )?const ${name} = `, "m").exec(source);
  if (!match) throw new Error(`no top-level const "${name}"`);
  let i = match.index + match[0].length;
  let depth = 0;
  for (; i < source.length; i++) {
    const c = source[i];
    if (c === '"' || c === "'" || c === "`") {
      for (i++; i < source.length && source[i] !== c; i++) {
        if (source[i] === "\\") i++;
      }
      continue;
    }
    if (c === "/" && source[i + 1] === "/") {
      i = source.indexOf("\n", i);
      continue;
    }
    if (c === "/" && source[i + 1] === "*") {
      i = source.indexOf("*/", i) + 1;
      continue;
    }
    if (c === "{" || c === "[" || c === "(") depth++;
    if (c === "}" || c === "]" || c === ")") depth--;
    if (c === ";" && depth === 0) {
      return source.slice(match.index + match[0].length, i).trim();
    }
  }
  throw new Error(`unterminated const "${name}"`);
}

/**
 * The compiled constants of one fork as a module, one `export const` per
 * name, in the order provenance.json lists them (a later constant may refer
 * to an earlier one, as `dynamicStyles` refers to `_temp`).
 */
export async function renderStyles(fork, entry) {
  const dir = packageDir(entry.package);
  let body =
    `/* eslint-disable */\n// @ts-nocheck\n// ${GENERATED_HEADER}\n//\n` +
    `// Compiled StyleX from ${entry.package} ${entry.version}, reused by the\n` +
    `// ${fork} fork so it renders with upstream's own class names\n` +
    `// (src/forks/compiled.ts). Copyright (c) Meta Platforms, Inc. and\n` +
    `// affiliates; MIT, see NOTICE.\n`;
  for (const { file, consts } of entry.styles.from) {
    const source = readFileSync(join(dir, file), "utf8");
    body += `\n// ${file}\n`;
    for (const name of consts) {
      body += `export const ${name} = ${extractConst(source, name)};\n`;
    }
  }
  const path = join(root, entry.styles.file);
  const config = (await prettier.resolveConfig(path)) ?? {};
  return prettier.format(body, { ...config, filepath: path });
}

/** Everything the drift guard compares, computed from the installed packages. */
export async function currentState() {
  const provenance = readProvenance();
  const out = {};
  for (const [fork, entry] of Object.entries(provenance)) {
    const dir = packageDir(entry.package);
    const files = {};
    for (const file of Object.keys(entry.files)) {
      const path = join(dir, file);
      files[file] = existsSync(path) ? sha256(path) : null;
    }
    out[fork] = {
      version: installedVersion(entry.package),
      files,
      styles: entry.styles ? await renderStyles(fork, entry) : undefined,
    };
  }
  return out;
}

async function main() {
  const accept = process.argv.includes("--accept");
  const provenance = readProvenance();
  const state = await currentState();
  for (const [fork, entry] of Object.entries(provenance)) {
    const now = state[fork];
    if (entry.styles) writeFileSync(join(root, entry.styles.file), now.styles);
    const changed = Object.keys(entry.files).filter(
      (f) => entry.files[f] !== now.files[f],
    );
    if (now.version !== entry.version || changed.length > 0) {
      console.log(
        `${fork}: ${entry.package} ${entry.version} -> ${now.version}` +
          (changed.length > 0 ? `; changed: ${changed.join(", ")}` : ""),
      );
    }
    if (accept) {
      entry.version = now.version;
      entry.files = now.files;
    }
  }
  if (accept) {
    const path = join(root, PROVENANCE);
    const config = (await prettier.resolveConfig(path)) ?? {};
    writeFileSync(
      path,
      await prettier.format(JSON.stringify(provenance), { ...config, filepath: path }),
    );
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
