/**
 * Export-surface drift guard (FR-4047).
 *
 * The mirrored Astryx surface, the root barrel and package.json#exports are
 * all generated by scripts/gen-exports.mjs and committed. This regenerates
 * them in memory and compares byte for byte, so a bump of any
 * @astryxdesign/* pin, or an edit to exports.exclude.json or
 * exports.customs.json, fails here until `pnpm run gen:exports` is re-run and
 * its diff reviewed.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";

import {
  generate,
  listMirrorFiles,
  type GenerateResult,
} from "../scripts/gen-exports.mjs";

const ROOT = join(__dirname, "..");

let result: GenerateResult;

beforeAll(async () => {
  result = await generate();
}, 120_000);

describe("generated export surface", () => {
  it("every generated file matches the committed copy", () => {
    const stale: string[] = [];
    for (const [path, content] of result.files) {
      let committed: string | undefined;
      try {
        committed = readFileSync(join(ROOT, path), "utf8");
      } catch {
        committed = undefined;
      }
      if (committed !== content) stale.push(path);
    }
    expect(stale, "run `pnpm run gen:exports` and review the diff").toEqual([]);
  });

  it("no mirror file is left over from an older Astryx", async () => {
    const generated = [...result.files.keys()].filter((p) =>
      p.startsWith("src/astryx/"),
    );
    expect(await listMirrorFiles()).toEqual(generated.sort());
  });

  it("package.json#exports matches the generated map, key order included", () => {
    const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as {
      exports: unknown;
    };
    expect(JSON.stringify(pkg.exports, null, 2)).toBe(
      JSON.stringify(result.exports, null, 2),
    );
  });
});

describe("export surface rules", () => {
  it("mirrors a core component at the same top-level subpath", () => {
    expect(result.exports["./Button"]).toEqual({
      types: "./dist/astryx/Button.d.ts",
      import: "./dist/astryx/Button.js",
    });
    expect(result.exports["./Table/utils"]).toBeDefined();
  });

  it("keeps the tokens subpath ending in .stylex, which the StyleX compiler keys on", () => {
    expect(Object.keys(result.exports)).toContain("./theme/tokens.stylex");
  });

  it("mirrors lab and the neutral theme under their prefixes", () => {
    for (const key of [
      "./lab",
      "./lab/lab.css",
      "./theme/neutral",
      "./theme/neutral/built",
      "./theme/neutral/theme.css",
    ]) {
      expect(Object.keys(result.exports)).toContain(key);
    }
  });

  it("mirrors lab name by name, so single lab names can be excluded", () => {
    const lab = result.files.get("src/astryx/lab.ts") ?? "";
    expect(lab).not.toMatch(/export \*/);
    expect(lab).toMatch(/^\s+Chart,$/m);
    expect(lab).toMatch(/^\s+ChartProps,$/m);
  });

  it("hides every excluded subpath and keeps its names out of the root barrel", () => {
    const exclusions = JSON.parse(
      readFileSync(join(ROOT, "exports.exclude.json"), "utf8"),
    ) as { name: string; exports?: string[]; replacedBy: string | null }[];
    for (const { name, exports, replacedBy } of exclusions) {
      // Names hidden from a mirror, and a same-name fork, keep the subpath.
      if (exports || replacedBy === name) continue;
      expect(Object.keys(result.exports)).not.toContain(`./${name}`);
    }
    const barrel = result.files.get("src/index.ts") ?? "";
    expect(barrel).not.toMatch(/^\s+Dialog,$/m);
    expect(result.report.droppedFromRoot).toContain("Dialog");
  });

  it("CSS mirrors are one @import of the Astryx sheet", () => {
    const css = [...result.files].filter(([path]) => path.endsWith(".css"));
    expect(css.length).toBeGreaterThan(0);
    for (const [path, content] of css) {
      const rules = content.replace(/\/\*[\s\S]*?\*\//g, "").trim();
      expect(rules, path).toMatch(/^@import "@astryxdesign\/[^"]+\.css";$/);
    }
  });

  it("no custom shadows an Astryx name: the 0.1 look-alikes are gone", () => {
    const barrel = result.files.get("src/index.ts") ?? "";
    expect(result.report.legacyCollisions).toEqual([]);
    for (const name of ["Button", "Badge", "Skeleton", "Tooltip", "EmptyState"]) {
      expect(barrel).not.toMatch(
        new RegExp(`export \\{[^}]*\\b${name}\\b[^}]*\\} from "\\./components`),
      );
    }
  });

  it("gives Modal its own subpath and keeps it in the root barrel", () => {
    expect(result.exports["./Modal"]).toEqual({
      types: "./dist/components/Modal/index.d.ts",
      import: "./dist/components/Modal/index.js",
    });
    const barrel = result.files.get("src/index.ts") ?? "";
    expect(barrel).toMatch(
      /export \{[^}]*\bModal,[^}]*\} from "\.\/components\/Modal"/,
    );
  });

  it("lets Modal re-export Dialog's own parts unchanged, and nothing else of Dialog", () => {
    expect([...result.report.reinstated].sort()).toEqual([
      "DialogHeader",
      "DialogHeaderProps",
      "DialogPosition",
      "DialogPurpose",
      "DialogVariant",
    ]);
    const barrel = result.files.get("src/index.ts") ?? "";
    expect(barrel).not.toMatch(/^\s+Dialog,$/m);
    expect(barrel).not.toMatch(/^\s+DialogProps,$/m);
  });

  it("names a replacement that exists for every exclusion", () => {
    const exclusions = JSON.parse(
      readFileSync(join(ROOT, "exports.exclude.json"), "utf8"),
    ) as { name: string; replacedBy: string | null }[];
    const customs = JSON.parse(
      readFileSync(join(ROOT, "exports.customs.json"), "utf8"),
    ) as { name: string }[];
    const dialog = exclusions.find((e) => e.name === "Dialog");
    expect(dialog?.replacedBy).toBe("Modal");
    expect(customs.map((c) => c.name)).toContain("Modal");
    const alertDialog = exclusions.find((e) => e.name === "AlertDialog");
    expect(alertDialog?.replacedBy).toBe("AlertModal");
    expect(customs.map((c) => c.name)).toContain("AlertModal");
  });

  it("hides AlertDialog behind AlertModal, which has its own subpath", () => {
    expect(Object.keys(result.exports)).not.toContain("./AlertDialog");
    expect(result.exports["./AlertModal"]).toEqual({
      types: "./dist/components/AlertModal/index.d.ts",
      import: "./dist/components/AlertModal/index.js",
    });
    const barrel = result.files.get("src/index.ts") ?? "";
    for (const name of [
      "AlertDialog",
      "AlertDialogProps",
      "useImperativeAlertDialog",
      "ImperativeAlertDialogReturn",
    ]) {
      expect(barrel).not.toMatch(new RegExp(`^\\s+${name},$`, "m"));
      expect(result.report.droppedFromRoot).toContain(name);
    }
  });
});

describe("forks of Astryx components", () => {
  const COMPLEX_SELECTOR_NAMES = [
    "ComplexSelector",
    "ComplexSelectorHandle",
    "ComplexSelectorProps",
    "ComplexSelectorRenderState",
    "ComplexSelectorSize",
    "ComplexSelectorStatus",
    "ComplexSelectorVariant",
  ];

  it("serves ComplexSelector's subpath from ui-common's copy", () => {
    expect(result.exports["./ComplexSelector"]).toEqual({
      types: "./dist/forks/ComplexSelector/index.d.ts",
      import: "./dist/forks/ComplexSelector/index.js",
    });
    expect(result.files.has("src/astryx/ComplexSelector.ts")).toBe(false);
  });

  it("exports every ComplexSelector name from the root, all from ui-common's copy", () => {
    const barrel = result.files.get("src/index.ts") ?? "";
    const fromFork = /export (?:type )?\{([^}]*)\} from "\.\/forks\/ComplexSelector"/g;
    const names = [...barrel.matchAll(fromFork)].flatMap((m) =>
      m[1]!
        .split(",")
        .map((n) => n.trim())
        .filter(Boolean),
    );
    expect(names.sort()).toEqual(COMPLEX_SELECTOR_NAMES);
    for (const name of COMPLEX_SELECTOR_NAMES) {
      expect(result.report.replaced).toContain(name);
    }
  });

  it("exports lab's Drawer and Tour from ui-common's copies, not lab", () => {
    const lab = result.files.get("src/astryx/lab.ts") ?? "";
    const [fromLab, ...own] = lab.split(/\n\/\/ (?=Drawer|Tour)/);
    for (const name of ["Drawer", "DrawerProps", "Tour", "TourStep", "useTour"]) {
      expect(fromLab).not.toMatch(new RegExp(`^\\s+${name},$`, "m"));
      expect(result.report.replaced).toContain(name);
    }
    expect(own.join("\n")).toContain('from "../forks/Drawer";');
    expect(own.join("\n")).toContain('from "../forks/Tour";');
  });
});
