/**
 * The cascade layer order and its injection into every shipped stylesheet.
 *
 * `scripts/layer-order.mjs` is the one definition. The build prepends its
 * statement to every stylesheet in `dist` (asserted on the packed artifact by
 * `scripts/check-pack.mjs`), and `scripts/check-fixture-styles.mjs` reads the
 * order a consumer bundle actually ends up with. This covers the functions
 * both rely on, and that the copies consumers read in the docs still spell the
 * same statement.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import {
  LAYER_ORDER,
  LAYER_ORDER_STATEMENT,
  effectiveLayerOrder,
  startsWithLayerOrder,
  withLayerOrder,
} from "../scripts/layer-order.mjs";

const ROOT = join(__dirname, "..");

describe("LAYER_ORDER_STATEMENT", () => {
  it("puts ui-common between Astryx's layers and the app's", () => {
    expect(LAYER_ORDER_STATEMENT).toBe(
      "@layer reset, theme, base, astryx-base, astryx-theme, ui-common, components, utilities;",
    );
    const at = (name: string) => LAYER_ORDER.indexOf(name);
    expect(at("ui-common")).toBeGreaterThan(at("astryx-theme"));
    expect(at("astryx-theme")).toBeGreaterThan(at("astryx-base"));
    expect(at("ui-common")).toBeLessThan(at("components"));
  });

  /**
   * Docs a consumer copies from. The upgrade tool's own copies live with the
   * tool and are held by its tests.
   */
  it.each([
    "README.md",
    "docs/astryx.md",
    "astryx.integration.mjs",
    "astryx/docs/ui-common.doc.mjs",
    "fixture/src/index.css",
  ])("%s spells the same statement", (file) => {
    const text = readFileSync(join(ROOT, file), "utf8");
    const copies = [...text.matchAll(/@layer reset,[^;]*;/g)].map((m) => m[0]);
    expect(copies.length).toBeGreaterThan(0);
    for (const copy of copies) expect(copy).toBe(LAYER_ORDER_STATEMENT);
  });
});

describe("withLayerOrder", () => {
  it("prepends the statement to a component sheet", () => {
    const css = "@layer ui-common{.uic-x{display:flex}}";
    const out = withLayerOrder(css);
    expect(out).toBe(`${LAYER_ORDER_STATEMENT}\n${css}`);
    expect(startsWithLayerOrder(out)).toBe(true);
    expect(startsWithLayerOrder(css)).toBe(false);
  });

  it("is idempotent", () => {
    const once = withLayerOrder("@layer ui-common{}");
    expect(withLayerOrder(once)).toBe(once);
  });

  it("keeps @charset first", () => {
    const out = withLayerOrder('@charset "UTF-8";\n.a{}');
    expect(out).toBe(`@charset "UTF-8";\n${LAYER_ORDER_STATEMENT}\n.a{}`);
    expect(startsWithLayerOrder(out)).toBe(true);
  });

  it("goes ahead of an @import mirror, where a layer statement is allowed", () => {
    const mirror =
      '/* @generated by scripts/gen-exports.mjs. Do not edit. */\n@import "@astryxdesign/core/astryx.css";\n';
    const out = withLayerOrder(mirror);
    expect(out.startsWith(LAYER_ORDER_STATEMENT)).toBe(true);
    expect(out.endsWith(mirror)).toBe(true);
  });

  it("accepts leading comments before the statement", () => {
    expect(startsWithLayerOrder(`/* a */\n/* b */\n${LAYER_ORDER_STATEMENT}`)).toBe(
      true,
    );
  });
});

describe("effectiveLayerOrder", () => {
  it("reads the order the bug produced: ui-common first", () => {
    const bundle = [
      "@layer ui-common{.uic-a{display:flex}}",
      "@layer reset{*{margin:0}}",
      "@layer theme,base;",
      "@layer astryx-base{.x{display:block}}",
      "@layer astryx-theme{:root{--c:red}}",
      "@layer components,utilities;",
    ].join("");
    expect(effectiveLayerOrder(bundle)).toEqual([
      "ui-common",
      "reset",
      "theme",
      "base",
      "astryx-base",
      "astryx-theme",
      "components",
      "utilities",
    ]);
  });

  it("reads a leading statement, and one a minifier folded into blocks", () => {
    const plain = `${LAYER_ORDER_STATEMENT}@layer ui-common{.a{}}@layer reset{}`;
    const folded =
      "@layer reset{}@layer theme,base;@layer astryx-base{}@layer astryx-theme{}" +
      "@layer ui-common{}@layer components,utilities;";
    expect(effectiveLayerOrder(plain)).toEqual([...LAYER_ORDER]);
    expect(effectiveLayerOrder(folded)).toEqual([...LAYER_ORDER]);
  });

  it("ignores nested layers, comments and strings", () => {
    const css =
      '/* @layer ui-common{ */ @layer reset{.a{content:"@layer ui-common{"}@layer inner{}}' +
      "@layer astryx-base{}";
    expect(effectiveLayerOrder(css)).toEqual(["reset", "astryx-base"]);
  });
});
