/* eslint-disable */
// @ts-nocheck
// @generated by scripts/sync-forks.mjs. Do not edit.
//
// Compiled StyleX from @astryxdesign/lab 0.6.5-canary.8701623, reused by the
// Drawer fork so it renders with upstream's own class names
// (src/forks/compiled.ts). Copyright (c) Meta Platforms, Inc. and
// affiliates; MIT, see NOTICE.

// dist/Drawer/Drawer.js
export const styles = {
  dialog: {
    kMv6JI: "x9ynric",
    kGuDYH: "xjm74w1",
    k63SB2: "xxovm9e",
    kLWn49: "xw6l6zx",
    kKX8nH: "x1j61x8r",
    k9WMMc: "x1yc453h",
    kJI5tL: "x7ssn7h",
    kTHuQy: "xzugeeo",
    kP9fke: "x6mezaz",
    kb6lSQ: "x1i21sxh",
    k4JVr9: "xp3md9m",
    kKMj4B: "x19pm5ym",
    khDVqt: "xeaf4i8",
    kTgw9: "x1lldw8n",
    kHjlTd: "x1h4wwuj",
    kE4Cay: "xxydokm",
    kVAEAm: "xixxii4",
    kogj98: "x1ghz6dp",
    kmVPX3: "x1717udv",
    kaIpWk: "x2u8bby",
    ks0D6T: "x1x1rfll",
    kskxy: "x7ab17h",
    kB7OPa: "x9f619",
    kXwgrk: "xdt5ytf",
    kWkggS: "x10xzikg",
    kGVxlE: "x1kcpxr7",
    kVQacm: "xb3r6kr",
    kZeWKH: "xish69e",
    kI3sdo: "x1a2a7pz",
    k87sOh: "x13vifvy",
    krVfgx: "x1ey2m1c",
    kZKoxP: "xtdtrs8",
    k1xSpc: "x1s85apg",
    k1ekBW: "x11xpdln",
    kIyJzY: "x80gvsz",
    kAMwcw: "xlr8y92",
    k6CgDc: "xzg1mie",
    $$css: true,
  },
  rendered: {
    k1xSpc: "x78zum5",
    $$css: true,
  },
  end: {
    kt4wiu: "xtijo5x",
    kLqNvP: "xhi6v0a",
    k2ei4v: "xgbv0en",
    kVhnKS: "x1t7ytsu",
    kGJrpR: "x1j92z86",
    k3aq6I: "xumwmo6 x1df3fe5",
    $$css: true,
  },
  endOpen: {
    k3aq6I: "xbryuvx x1yqmsfc x1lymnkk",
    $$css: true,
  },
  start: {
    kLqNvP: "x1o0tod",
    kt4wiu: "x1woyocn",
    ke9TFa: "xw8tdv1",
    k8ry5P: "x18b5jzi",
    kBCPoo: "x1gejf6u",
    k3aq6I: "x5i6ehr xttggg",
    $$css: true,
  },
  startOpen: {
    k3aq6I: "xbryuvx x6mt36l x14gflnl",
    $$css: true,
  },
  scrim: {
    kGyWv1: "xnixb3f",
    kba3nw: "x1abwkk1",
    k5sjJv: "xph5o2a",
    kND0Po: "x167zut7",
    k9an0g: "xft5bk6",
    kb4ib: "x15h3t91",
    kA5Tbj: "x1viac0w",
    $$css: true,
  },
  scrimOpen: {
    k5sjJv: "xb3n6bw xxiuuzi",
    $$css: true,
  },
};
export const _temp = {
  ks0D6T: "xlbgzzq",
  $$css: true,
};
export const dynamicStyles = {
  inlineSize: (desktopWidth, mobileWidth) => [
    _temp,
    {
      kzqmXN:
        (desktopWidth != null ? "x11ymkkh " : desktopWidth) +
        (mobileWidth != null ? "xci7e5a" : mobileWidth),
      $$css: true,
    },
    {
      "--x-1xmrurk": ((val) =>
        typeof val === "number" ? val + "px" : val != null ? val : undefined)(
        desktopWidth,
      ),
      "--x-fqzwsx": ((val) =>
        typeof val === "number" ? val + "px" : val != null ? val : undefined)(
        mobileWidth,
      ),
    },
  ],
};
